---
- name: Install nginx
  yum: 
    name: nginx
    state: latest

- name: Configure proxy_pass
  template: 
    src: nginx.conf 
    dest: /etc/nginx/
    owner: root
    group: root

- name: Start nginx
  service: 
    name: nginx 
    state: started 
    enabled: yes
  notify: 
    - restart nginx
