---
- name: Install Java
  yum:
    name: java
    state: latest

- name: add group "tomcat"
  group:
    name: tomcat
    state: present
    system: yes

- name: add user "tomcat"
  user:
    name: tomcat
    group: tomcat
    system: yes
    state: present
    #shell: /bin/false
    home: /usr/share/tomcat
    create_home: no

- name: Download Tomcat
  get_url:
    url: http://archive.apache.org/dist/tomcat/tomcat-7/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
    dest: /opt/apache-tomcat-{{ tomcat_version }}.tar.gz
    mode: 0664

- name: Extract archive
  unarchive:
    src: /opt/apache-tomcat-{{ tomcat_version }}.tar.gz
    creates: /opt/apache-tomcat-{{ tomcat_version }}
    dest: /opt/
    remote_src: yes

- name: Symlink install directory
  file:
    src: /opt/apache-tomcat-{{ tomcat_version }}
    path: /usr/share/tomcat state=link

- name: Configure Tomcat server
  template:
    src: server.xml
    dest: /usr/share/tomcat/conf/

- name: Configure Tomcat users
  template:
    src: tomcat-users.xml
    dest: /usr/share/tomcat/conf/

- name: adding manager.xml
  template:
    src: manager.xml
    dest: /usr/share/tomcat/conf/Catalina/localhost/

- name: Install Tomcat init script
  copy:
    src: tomcat-initscript.sh
    dest: /etc/init.d/tomcat mode=0755

- name: Adding sample war file
  get_url:
    url: https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
    dest: /usr/share/tomcat/webapps/sample.war

- name: Change ownership of Tomcat installation
  file:
    path: /usr/share/tomcat/
    owner: tomcat
    group: tomcat
    state: directory
    recurse: yes
  notify:
    - restart tomcat

- name: Start Tomcat
  service:
    name: tomcat
    state: started
    enabled: yes

- name: wait for tomcat to start
  wait_for:
    port: {{ http_port }}
